### ISSUE TITLE
authenticatorGetInfo should use defaults for options

### ISSUE THREAD

**Issue by cheburashka** [google/CTAP2-test-tool#85] opened 2020-11-17 23:04 UTC
Thanks for this tooI. I had an error indicating `Check failed: condition Failed critical condition: User presence support expected.` because in the authenticatorGetInfo response the authenticator is not including the `up` flag.  However, according to the specification (and the conformance tests) _When an option is not present, the default is applied per table below_ so this option being absent is a valid configuration and the tool should instead use the default.

Do you agree to add this fix to the backlog?

**Comment by kaczmarczyck** [comment] 2020-11-23 17:22
Hi! Thanks for reporting this bug. I'll merge the fix after you confirm it works for you.

May I ask what security key you are testing? (In case it's something I can buy for the next round of testing / reproducing tests.)

**Comment by kaczmarczyck** [comment] 2020-11-30 09:50
It works for me, so I'm closing this issue. Please let me know if you still have problems!

**Closed** 2020-11-30 09:50 UTC
Labels: bug

**Comment by cheburashka** [comment] 2020-12-03 19:58
Thanks, I confirm this works now. I'm using [Crescendo Keys](https://www.hidglobal.com/products/cards-and-credentials/crescendo/crescendo-key), I can send you some if you can send me your contact details to acastillo_at_hidglobal_dot_com
